name: Gemini Classifications Pipeline

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    strategy:
      # matrix will contain 20 items; see below (you'll paste/generated list)
      matrix:
        include:
          - start: 0
            end: 1
            gemini_secret: GEMINI_API_KEY
          - start: 1
            end: 2
            gemini_secret: GEMINI_API_KEY_MARCUS
          - start: 2
            end: 3
            gemini_secret: GEMINI_API_KEY_JONATAN
          - start: 3
            end: 4
            gemini_secret: GEMINI_API_KEY_WADE
          - start: 4
            end: 5
            gemini_secret: GEMINI_API_KEY_JORGE
          

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "credentials.json"
        json: ${{ secrets.STORAGE_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL script
      env:
        START_INDEX: ${{ matrix.start }}
        END_INDEX:   ${{ matrix.end }}
        STORAGE_KEY: ${{ secrets.STORAGE_KEY }}        
        API_KEY: ${{ secrets.API_KEY }}
        GEMINI_API_KEY: ${{ secrets[matrix.gemini_secret] }}
        
      run: |
        python gemini_classification.py
